#!/usr/bin/env python3
"""Sync marketing-site question/exam/path counts from the app's source of truth.

The Azure Mastery marketing site hard-codes per-exam question counts and a few
aggregate totals (total questions, exam count, certification-path count) in
~30 static HTML files, repeated ~10x per page across <title>, meta, OpenGraph,
Twitter, JSON-LD, body copy, hero stats and cross-referencing "related" cards.
Hand-maintaining those drifts badly (19/27 pages were stale when this was
written). This script makes the app the single source of truth.

Source of truth (the app repo, a sibling checkout):
  - headline totals = App/AppStoreAssets/catalog-totals.json, generated by the
      app's Tools/generate-exam-catalog.py and gated in its CI. Read verbatim,
      never recomputed here, so the site and the App Store listing cannot drift.
  - per-exam question count = examQuestionCount from
      App/AzureMastery/Resources/exam-catalog.json
  - exam retirement dates = lifecycle.retirementDate from the same file
  - certification-path count = `CertPathDefinition(` occurrences in
      App/AzureMastery/Data/CertPathRegistry.swift minus the legacy ones
      (`replacedByPathID:`), mirroring CertPathRegistry.currentPaths

A snapshot is committed to data/exam-counts.json so the marketing repo is
self-contained (re-runnable without the app checkout). Refresh it with --refresh.

Only exams a candidate can still book are advertised. The app decides which
those are: an exam carrying any retirement date is classified non-current and
its examQuestionCount drops to 0, which is exactly the test used here. Such an
exam leaves every aggregate but keeps its own /exams/<code>/ page, its llms.txt
bullet and its per-page count (falling back to the full bank size), because
those still serve people searching for the dead exam.

Counts are exam-scoped, not raw bank sizes. The app's blueprint classifier
splits each bank into exam-scoped and supplemental questions and advertises only
the former, so a page reads "481 AZ-104 practice questions" against a 651-question
bank. Aggregates and per-exam pages must stay on that one basis or they stop
summing.

Aggregates shown on the homepage use the current App Store marketing rule:
round the total DOWN to the nearest 100 and append "+".  e.g. 11,728 ->
"11,700+".  The animated metric counter
parses leading digits only (regex ^(\\d+)(.*)), so commas would break it — the
metric stays comma-less ("10000") while prose uses the formatted "10,000+".

Two standalone social images (the LinkedIn banner and the OpenGraph card) bake
those same aggregates into pixels, so text-patching their HTML is not enough —
this script also re-renders them to PNG via headless Chrome. Their exam-pill
lists are NOT auto-generated (each pill is hand-coloured and grouped); instead
the script warns when the pills shown drift from the catalogue so a human can
add or remove the one that changed.

Usage:
  python3 Tools/sync-marketing-counts.py --refresh      # re-read app repo -> data file
  python3 Tools/sync-marketing-counts.py                # patch HTML + render social PNGs
  python3 Tools/sync-marketing-counts.py --check        # report drift, change nothing
  python3 Tools/sync-marketing-counts.py --social-only  # only the banner + og-image
  python3 Tools/sync-marketing-counts.py --no-render    # patch HTML/counts, skip PNG render

App repo location defaults to the sibling "../AZ-104 Mastery"; override with
env AZURE_MASTERY_APP_REPO. Rendering needs Google Chrome (or Chromium); override
the binary with env CHROME.
"""

from __future__ import annotations

import argparse
import functools
import html
import http.server
import json
import os
import re
import shutil
import subprocess
import sys
import threading

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(ROOT, "data", "exam-counts.json")
EXAMS_DIR = os.path.join(ROOT, "exams")
INDEX_HTML = os.path.join(ROOT, "index.html")
LLMS_TXT = os.path.join(ROOT, "llms.txt")

# Standalone social images: hand-built HTML rendered to PNG (the aggregates are
# baked into pixels, so these must be re-rendered, not just text-patched).
BANNER_HTML = os.path.join(ROOT, "apps", "AzureMastery", "linkedin-banner.html")
BANNER_PNG = os.path.join(ROOT, "images", "linkedin-banner.png")
OG_HTML = os.path.join(ROOT, "apps", "AzureMastery", "og-image.html")
OG_PNG = os.path.join(ROOT, "images", "og-image.png")
# Codes shown as styled exam pills in each image (e.g. "AZ-104"). Hand-coloured,
# so we only warn on drift rather than regenerate them.
PILL_RE = re.compile(r'class="(?:exam-tag exam-tag--|pill pill-)[a-z]+">([A-Z]{2}-\d{3})<')

# Per-exam OG cards (Task A8): one template, filled per code and rendered to a
# throwaway temp HTML under apps/AzureMastery/ so its "../../images/" relative
# asset paths keep resolving, then screenshotted like the two shared images.
# Unlike those two (which stay PNG), per-exam cards are converted to JPEG after
# render -- see convert_to_jpeg() -- because a mostly-text/gradient card with no
# embedded photos compresses far better as quality-82 JPEG than as a palette PNG.
OG_EXAM_HTML = os.path.join(ROOT, "apps", "AzureMastery", "og-exam.html")
OG_EXAM_TMP = os.path.join(ROOT, "apps", "AzureMastery", "_og-exam-render-tmp.html")
OG_DIR = os.path.join(ROOT, "images", "og")
# The pill text as it reads once {{COUNT}} has been filled in; swapped for the
# retired variant by exact match rather than re-deriving it, so a change to the
# template's pill copy can't silently desync the two.
PILL_COUNT_RE = re.compile(r'<div class="pill">\d+ practice questions · free to start</div>')
PILL_RETIRED = '<div class="pill pill--retired">Retired exam · successor inside</div>'
# The per-page accent custom properties every exams/<code>/index.html declares
# in a one-line <style> (e.g. `--amh-accent: #50E6FF; --amh-accent-2: #2B88D8;`).
# Falls back to the app's default cyan/blue when a page has none.
ACCENT_RE = re.compile(
    r'--amh-accent:\s*(#[0-9A-Fa-f]{6});\s*--amh-accent-2:\s*(#[0-9A-Fa-f]{6})')
DEFAULT_ACCENT = ("#50E6FF", "#2B88D8")

DEFAULT_APP_REPO = os.environ.get(
    "AZURE_MASTERY_APP_REPO",
    os.path.join(os.path.dirname(ROOT), "AZ-104 Mastery"),
)

# Word forms for the homepage headline-accent ("Twenty-eight certifications.").
_ONES = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
_TEENS = ["ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen",
          "sixteen", "seventeen", "eighteen", "nineteen"]
_TENS = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]


def number_word(n: int) -> str:
    """Capitalised English word for 0..99 (enough for exam counts)."""
    if n < 10:
        w = _ONES[n]
    elif n < 20:
        w = _TEENS[n - 10]
    elif n < 100:
        w = _TENS[n // 10] + ("-" + _ONES[n % 10] if n % 10 else "")
    else:
        return str(n)
    return w[0].upper() + w[1:]


# ── code helpers ──────────────────────────────────────────────────────────

def slug_to_code(slug: str) -> str:
    """az104 -> AZ-104 ; gh900 -> GH-900."""
    m = re.match(r"([a-z]+)(\d+)", slug)
    return f"{m.group(1).upper()}-{m.group(2)}"


def code_to_dir(code: str) -> str:
    """AZ-104 -> az-104 (the /exams/<dir>/ folder name)."""
    return code.lower()


def exam_accent(code: str) -> tuple[str, str]:
    """Read (--amh-accent, --amh-accent-2) from the exam's own page so its OG
    card matches the page's colour, falling back to the app's default cyan/blue
    when the page is missing or carries no accent (should not happen -- every
    shipped exams/<code>/index.html declares one)."""
    page = os.path.join(EXAMS_DIR, code_to_dir(code), "index.html")
    if os.path.exists(page):
        m = ACCENT_RE.search(open(page).read())
        if m:
            return m.group(1), m.group(2)
    return DEFAULT_ACCENT


# ── data file ─────────────────────────────────────────────────────────────

def refresh_from_app(app_repo: str) -> dict:
    catalog = os.path.join(app_repo, "App", "AzureMastery", "Resources", "exam-catalog.json")
    if not os.path.exists(catalog):
        sys.exit(f"error: app catalogue not found at {catalog}\n"
                 f"set AZURE_MASTERY_APP_REPO to the AZ-104 Mastery checkout.")
    with open(catalog) as fh:
        entries = json.load(fh)["exams"]

    # examQuestionCount is the blueprint-classified, exam-scoped count the app
    # advertises. It is 0 for a non-current exam; those pages fall back to the
    # full bank size so a retired page still states what it actually contains.
    # `name` is snapshotted too (Task A8) so the per-exam OG card render loop
    # and CI never need their own app-repo checkout to know an exam's title.
    exams, banks, retirement, retired, names = {}, {}, {}, [], {}
    for entry in entries:
        code = entry["code"]
        scoped = entry.get("examQuestionCount") or 0
        banks[code] = entry["questionCount"]
        exams[code] = scoped or entry["questionCount"]
        names[code] = entry["name"]
        if not scoped:
            retired.append(code)
        date = (entry.get("lifecycle") or {}).get("retirementDate")
        if date:
            retirement[code] = date

    totals_path = os.path.join(app_repo, "App", "AppStoreAssets", "catalog-totals.json")
    if not os.path.exists(totals_path):
        sys.exit(f"error: generated totals not found at {totals_path}\n"
                 f"run Tools/generate-exam-catalog.py in the app repo first.")
    with open(totals_path) as fh:
        totals = json.load(fh)
    if totals["examCount"] != len(exams) - len(retired):
        print(f"  warning: catalog-totals.json counts {totals['examCount']} current exams "
              f"but the catalogue has {len(exams) - len(retired)} with exam-scoped questions.")

    registry = os.path.join(app_repo, "App", "AzureMastery", "Data", "CertPathRegistry.swift")
    cert_paths = None
    if os.path.exists(registry):
        # A path is legacy when it declares replacedByPathID (CertPathDefinition
        # .isLegacy), so subtract those to land on CertPathRegistry.currentPaths.
        swift = open(registry).read()
        defined = swift.count("CertPathDefinition(")
        legacy = swift.count("replacedByPathID:")
        if not 0 < legacy < defined:
            print(f"  warning: read {legacy} legacy of {defined} cert paths, which looks wrong — "
                  f"check CertPathRegistry.swift still spells `replacedByPathID:` inline.")
        cert_paths = defined - legacy

    data = {"exams": exams, "bank_totals": banks, "retired": sorted(retired),
            "retirement_dates": retirement, "totals": totals,
            "cert_path_count": cert_paths, "names": names}
    os.makedirs(os.path.dirname(DATA_FILE), exist_ok=True)
    with open(DATA_FILE, "w") as fh:
        json.dump(data, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print(f"refreshed {DATA_FILE}: {len(exams)} banks, {len(retired)} non-current; "
          f"advertising {totals['examCount']} exams / {totals['questionCountLabel']} "
          f"({totals['questionCount']} exam-scoped of {sum(banks.values())} authored), "
          f"{cert_paths} current cert paths")
    return data


def load_data() -> dict:
    if not os.path.exists(DATA_FILE):
        sys.exit(f"error: {DATA_FILE} missing — run with --refresh first.")
    with open(DATA_FILE) as fh:
        return json.load(fh)


def non_current_exams(data: dict) -> set:
    """Exam codes the app classifies as non-current — every exam carrying a
    Microsoft retirement date. Excluded from all advertised aggregates and shown
    under the retired groupings. Decided in the app repo, mirrored here."""
    return set(data.get("retired") or ())


# ── patching ──────────────────────────────────────────────────────────────

class Patcher:
    def __init__(self, check_only: bool):
        self.check_only = check_only
        self.changed_files = 0
        self.total_edits = 0
        self.problems = 0        # hand-fixes the script cannot make itself

    def apply(self, path: str, edits, transforms=()) -> None:
        """edits: list of (regex, replacement) applied in order.
        transforms: callables text -> (text, edits), for counts that have to be
        derived from the document itself rather than written as a fixed number."""
        if not os.path.exists(path):
            print(f"  skip (missing): {os.path.relpath(path, ROOT)}")
            return
        original = open(path).read()
        text = original
        n = 0
        for pattern, repl in edits:
            text, k = re.subn(pattern, repl, text)
            n += k
        for transform in transforms:
            text, k = transform(text)
            n += k
        rel = os.path.relpath(path, ROOT)
        if text != original:
            self.changed_files += 1
            self.total_edits += n
            if self.check_only:
                print(f"  DRIFT  {rel}: {n} replacement(s) would change content")
            else:
                with open(path, "w") as fh:
                    fh.write(text)
                print(f"  synced {rel}: {n} replacement(s)")


def exam_page_edits(code: str, count: int):
    """Anchored, value-agnostic edits for a single exam page."""
    c = str(count)
    return [
        # hero stat span
        (r'(am-cert-hero__stat-count">)\d+', r'\g<1>' + c),
        # "<n> AZ-900 practice questions" / "... cert-specific questions"
        (rf'\b\d+(\s+{re.escape(code)}\s+(?:practice|cert-specific)\s+questions)', c + r'\1'),
        # bare "<n> cert-specific questions" (own page only — related cards say "practice questions")
        (r'\b\d+(\s+cert-specific\s+questions)', c + r'\1'),
        # "with <n> AZ-900 practice" (meta/JSON-LD lead-ins without the word "questions" adjacent)
        (rf'\b\d+(\s+{re.escape(code)}\s+practice\b)', c + r'\1'),
        # "full <n>-question bank" in the exam simulator copy
        (r'(full\s+)\d+(-question\s+bank)', r'\g<1>' + c + r'\2'),
        # title/og:title/twitter:title pattern "AZ-700 Practice Questions — 396 Qs"
        (rf'({re.escape(code)} Practice Questions — )\d+( Qs)', r'\g<1>' + c + r'\2'),
        # app-FAQ JSON-LD/visible copy "full bank of <n> AZ-700 practice questions"
        (rf'(full bank of )\d+( {re.escape(code)} practice questions)', r'\g<1>' + c + r'\2'),
    ]


def patch_related_cards(text: str, counts: dict) -> tuple[str, int]:
    """In each <a class="related-card" href="/exams/<dir>/"> ... </a> block,
    rewrite the bare "<n> practice questions" hint to the linked exam's count."""
    edits = 0

    def repl(m):
        nonlocal edits
        block = m.group(0)
        href = re.search(r'href="/exams/([a-z]+-\d+)/"', block)
        if not href:
            return block
        code = href.group(1).upper()
        if code not in counts:
            return block
        new_block, k = re.subn(r'\b\d+(\s+practice\s+questions)',
                               str(counts[code]) + r'\1', block)
        edits += k
        return new_block

    text = re.sub(r'<a class="related-card"[^>]*>.*?</a>', repl, text, flags=re.S)
    return text, edits


def homepage_edits(total_label: str, metric_total: str, exam_count: int,
                   cert_paths: int, retired_count: int, catalogue_count: int):
    """Anchored aggregate edits for index.html. Each pattern is keyed off stable
    surrounding text so per-pillar roadmap counts ('5 exams') are never touched."""
    ec = str(exam_count)
    cp = str(cert_paths)
    return [
        # ── total questions (prose: "9,000 questions", "9,000 practice questions", "9,000 Questions") ──
        # Require a thousands-grouped number (>=1 comma-group) and a lookbehind so we never
        # start mid-number. This excludes exam codes ("AZ-204 practice questions") and bare
        # keyword commas ("exam prep, practice questions") — both must stay untouched.
        (r'(?<![\d,])\d{1,3}(?:,\d{3})+\+?(\s+(?:practice\s+)?[Qq]uestions)', total_label + r'\1'),
        # ── metric counters (anchored on the adjacent metric-label) ──
        (r'(class="metric-number[^"]*"[^>]*>)\d+\+?(</span>\s*<span class="metric-label">Questions)',
         r'\g<1>' + metric_total + r'\2'),
        (r'(class="metric-number[^"]*"[^>]*>)\d+(</span>\s*<span class="metric-label">Exams)',
         r'\g<1>' + ec + r'\2'),
        # ── exam count (each anchored to a stable phrase) ──
        (r'\|\s*\d+(\s+Exams</title>)', '| ' + ec + r'\1'),
        (r'\b\d+(\s+Microsoft\s+certification\s+exams)', ec + r'\1'),
        (r'across\s+\d+(\s+Microsoft\s+[Ee]xams)', 'across ' + ec + r'\1'),
        (r'across\s+\d+(\s+[Ee]xams)\b', 'across ' + ec + r'\1'),
        (r'\b\d+(\s+Microsoft\s+[Ee]xams)\b', ec + r'\1'),
        (r'Browse\s+the\s+\d+(\s+exams)', 'Browse the ' + ec + r'\1'),
        (r'\b\d+(\s+exams\s+spanning)', ec + r'\1'),
        # ── certification paths ──
        (r'\b\d+(\s+certification\s+paths)', cp + r'\1'),
        (r'\b\d+(\s+certification\s+routes)', cp + r'\1'),
        (r'\b\d+(\s+guided\s+certification\s+paths)', cp + r'\1'),
        # ── headline word-number "Twenty-six certifications." -> exam count word ──
        (r'(headline-accent">)[A-Za-z-]+(\s+certifications\.)',
         r'\g<1>' + number_word(exam_count) + r'\2'),
        # ── "Retired & retiring (N)" disclosure summaries (hero + footer) ──
        (r'(exam-retired-disclosure__summary">Retired &amp; retiring \()\d+(\))',
         r'\g<1>' + str(retired_count) + r'\2'),
        # ── JSON-LD ItemList entity count. This is deliberately NOT exam_count:
        # entity list = sit-able + retired reference pages, not the advertised
        # exam count — the ItemList enumerates every /exams/<code>/ page that
        # exists, current or retired, so search engines can still find retired
        # exam reference pages. ──
        (r'("numberOfItems":\s*)\d+', r'\g<1>' + str(catalogue_count)),
    ]


def patch_roadmap_category_counts(text: str, retired: set):
    """Rewrite each roadmap pillar's "<n> exams" chip to the number of sit-able
    exams pilled under it. Counted from the lifecycle set rather than from the
    exam-link--retired class, so stale markup cannot yield a stale count."""
    edits = 0
    seen = dict.fromkeys(
        re.findall(r'<div class="roadmap-category" data-category="([a-z-]+)"', text))
    for cat in seen:
        codes = []
        for cell in re.findall(rf'<div class="roadmap-cell" data-category="{cat}">(.*?)</div>',
                               text, flags=re.S):
            codes += re.findall(r'href="/exams/([a-z]+-\d+)/"', cell)
        n = sum(1 for c in codes if c.upper() not in retired)
        label = f"{n} exam" + ("s" if n != 1 else "")
        before = text
        text = re.sub(
            rf'(<div class="roadmap-category" data-category="{cat}">'
            rf'.*?roadmap-category__count">)[^<]*(</span>)',
            r'\g<1>' + label + r'\g<2>', text, count=1, flags=re.S)
        edits += text != before
    return text, edits


def patch_llms_section_counts(text: str, retired: set):
    """Rewrite each "### Group name (N)" heading in llms.txt to the number of
    sit-able exams bulleted under it. Retired exams keep their bullets — the
    heading counts what you can still book, the list stays a full reference."""
    edits = 0

    def repl(m):
        nonlocal edits
        title, shown, body = m.group(1), int(m.group(2)), m.group(3)
        codes = re.findall(r'^-\s+\[?([A-Z]{2}-\d{3})\b', body, flags=re.M)
        n = sum(1 for c in codes if c not in retired)
        if not codes or n == shown:
            return m.group(0)
        edits += 1
        return f"### {title} ({n})\n{body}"

    text = re.sub(r'^### (.+?) \((\d+)\)\n(.*?)(?=^#{2,3} |\Z)', repl, text,
                  flags=re.M | re.S)
    return text, edits


def patch_exam_code_lists(text: str, retired: set):
    """Drop retired codes from the homepage's spelled-out exam lists.

    The meta description, og:image:alt, JSON-LD keywords and the two "Azure Mastery
    covers N exams: ..." FAQ answers each enumerate every code. Leaving a retired
    code in a list introduced by a sit-able count reads as a miscount, so the list
    and the number have to move together. Rejoins in the list's own style — Oxford
    comma, bare "and", or neither."""
    def repl(m):
        run = m.group(0)
        codes = re.findall(r'[A-Z]{2}-\d{3}', run)
        kept = [c for c in codes if c not in retired]
        if len(kept) == len(codes) or len(kept) < 2:
            return run
        if re.search(r',\s+and\s+[A-Z]{2}-\d{3}$', run):
            return ", ".join(kept[:-1]) + ", and " + kept[-1]
        if re.search(r'\s+and\s+[A-Z]{2}-\d{3}$', run):
            return ", ".join(kept[:-1]) + " and " + kept[-1]
        return ", ".join(kept)

    # 3+ codes joined by ", " (optionally "and" before the last) — long enough to be
    # a catalogue enumeration, never a two-exam comparison in body copy.
    return re.subn(r'[A-Z]{2}-\d{3}(?:(?:,\s+|,?\s+and\s+)[A-Z]{2}-\d{3}){2,}', repl, text)


def patch_more_certifications(text: str, exam_count: int, retired: set):
    """The SEO h1 names a handful of exams then says "and <n> More Microsoft
    Certifications" — n has to be the sit-able total minus the ones already named."""
    def repl(m):
        named = {c for c in re.findall(r'[A-Z]{2}-\d{3}', m.group(1))} - retired
        return f"{m.group(1)}and {exam_count - len(named)} More"

    return re.subn(r'((?:[A-Z]{2}-\d{3},\s+)+)and \d+ More(?= Microsoft Certifications)',
                   repl, text)


def warn_retired_markup(p: "Patcher", retired: set, catalogue: set) -> None:
    """Report exam links whose retired treatment disagrees with the catalogue.

    The homepage marks retired exams with class="... exam-link--retired"; the
    /exams/ hub instead groups them under its #fam-retired section. Both are
    hand-maintained, so this is what catches an exam whose retirement date passed
    while nobody was looking. It only reports — the markup moves are a human's job
    (each link carries hand-written aria-label and grouping)."""
    print("retired markup:")
    problems = []

    if os.path.exists(INDEX_HTML):
        stale, premature = {}, {}
        for tag in re.findall(r'<a\b[^>]*>', open(INDEX_HTML).read()):
            href = re.search(r'href="/exams/([a-z]+-\d+)/"', tag)
            if not href:
                continue
            code = href.group(1).upper()
            marked = "exam-link--retired" in tag
            if code in retired and not marked:
                stale[code] = stale.get(code, 0) + 1
            elif code not in retired and marked:
                premature[code] = premature.get(code, 0) + 1
        for code, n in sorted(stale.items()):
            problems.append(f"index.html: {code} is non-current, but {n} link(s) still styled "
                            f"active — add exam-link--retired and move it into the disclosures")
        for code, n in sorted(premature.items()):
            problems.append(f"index.html: {code} is current, but {n} link(s) styled non-current")

    hub = os.path.join(EXAMS_DIR, "index.html")
    if os.path.exists(hub):
        text = open(hub).read()
        section = re.search(r'<section id="fam-retired".*?</section>', text, flags=re.S)
        grouped = {c.upper() for c in
                   re.findall(r'href="/exams/([a-z]+-\d+)/"', section.group(0))} if section else set()
        listed = {c.upper() for c in re.findall(r'href="/exams/([a-z]+-\d+)/"', text)}
        for code in sorted((retired & listed) - grouped):
            problems.append(f"exams/index.html: {code} is non-current but sits outside #fam-retired")
        for code in sorted(grouped - retired):
            problems.append(f"exams/index.html: {code} is current but sits under #fam-retired")
        for code in sorted(catalogue - retired - listed):
            problems.append(f"exams/index.html: {code} is current and has a page but no hub card")

    if not problems:
        print("  markup ok  retired treatment matches the catalogue")
        return
    for line in problems:
        print(f"  RETIRED   {line}")
    p.problems += len(problems)


def warn_itemlist_count(catalogue_count: int) -> None:
    """Report when the homepage JSON-LD ItemList's ListItem entries drift from
    catalogue_count. The ItemList deliberately enumerates every exam page that
    exists — entity list = sit-able + retired reference pages, not the
    advertised exam count — so this only warns; homepage_edits() is what keeps
    numberOfItems itself in sync."""
    if not os.path.exists(INDEX_HTML):
        return
    text = open(INDEX_HTML).read()
    m = re.search(r'"@type":\s*"ItemList".*?</script>', text, flags=re.S)
    if not m:
        print("  warning: homepage has no JSON-LD ItemList block to check.")
        return
    n = m.group(0).count('"@type": "ListItem"')
    if n != catalogue_count:
        print(f"  warning: homepage ItemList has {n} ListItem entries, but the "
              f"catalogue has {catalogue_count} exams — re-run with --refresh "
              f"or check index.html.")


def llms_edits(counts: dict, total_label: str, exam_count: int):
    """Counts in llms.txt: the header summary + the per-exam bullet list.
    Each bullet is '...(/exams/<dir>/): <n> in-app practice questions...'."""
    ec = str(exam_count)
    edits = [
        # header: "9,000+ practice questions cover 27 Microsoft certification exams"
        (r'\b[\d,]+\+?(\s+practice\s+questions\s+cover)', total_label + r'\1'),
        (r'cover\s+\d+(\s+Microsoft\s+certification\s+exams)', 'cover ' + ec + r'\1'),
        (r'## Exams covered \(\d+\)', f'## Exams covered ({ec})'),
    ]
    for code, n in counts.items():
        dir_ = code_to_dir(code)
        # Use \g<N> (not \1\2) — a bare \1 followed by digits, e.g. "\1" + "358",
        # would be misread by re as group reference \1358 / \13.
        edits.append(
            (rf'(/exams/{re.escape(dir_)}/\):\s*)\d+(\s+in-app\s+practice\s+questions)',
             r'\g<1>' + str(n) + r'\g<2>'))
    return edits


# ── social images (banner + og-image) ──────────────────────────────────────

def banner_edits(total_label: str, exam_count: int):
    """Anchored aggregate edits for linkedin-banner.html. Keyed off the stat-label
    text so only the two headline numbers (Questions, Exams) are ever touched."""
    return [
        (r'(stat-number stat-number--cyan">)[\d,]+\+?'
         r'(</div>\s*<div class="stat-label">Practice Questions)',
         r'\g<1>' + total_label + r'\g<2>'),
        (r'(stat-number stat-number--purple">)\d+'
         r'(</div>\s*<div class="stat-label">Exams)',
         r'\g<1>' + str(exam_count) + r'\g<2>'),
    ]


def og_edits(total_label: str, exam_count: int, cert_paths: int):
    """Anchored aggregate edits for og-image.html's stats bar (Exams • Questions •
    Cert Paths). Each number is keyed off its trailing label span."""
    return [
        (r'(stat-num stat-num--cyan">)\d+(</span>Exams)',
         r'\g<1>' + str(exam_count) + r'\g<2>'),
        (r'(stat-num stat-num--gold">)[\d,]+\+?(</span>Questions)',
         r'\g<1>' + total_label + r'\g<2>'),
        (r'(stat-num stat-num--green">)\d+(</span>Cert Paths)',
         r'\g<1>' + str(cert_paths) + r'\g<2>'),
    ]


def warn_pill_drift(path: str, counts: dict, exam_count: int) -> None:
    """Print a warning if the exam pills shown on an image drift from the catalogue.
    Pills are hand-coloured/grouped, so this only reports — it never rewrites them."""
    if not os.path.exists(path):
        return
    shown = set(PILL_RE.findall(open(path).read()))
    rel = os.path.relpath(path, ROOT)
    missing = sorted(set(counts) - shown)   # in catalogue, absent from image
    extra = sorted(shown - set(counts))     # on image, absent from catalogue
    if not missing and not extra and len(shown) == exam_count:
        print(f"  pills ok  {rel}: all {exam_count} exams shown")
        return
    print(f"  PILLS     {rel}: shows {len(shown)}, catalogue has {exam_count}")
    if missing:
        print(f"            add by hand:    {', '.join(missing)}")
    if extra:
        print(f"            remove by hand: {', '.join(extra)}")


def find_chrome() -> str | None:
    """Locate a Chrome/Chromium binary (env CHROME wins)."""
    env = os.environ.get("CHROME")
    if env and os.path.exists(env):
        return env
    mac = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    if os.path.exists(mac):
        return mac
    chromium = "/Applications/Chromium.app/Contents/MacOS/Chromium"
    if os.path.exists(chromium):
        return chromium
    for name in ("google-chrome", "google-chrome-stable", "chromium",
                 "chromium-browser", "chrome"):
        found = shutil.which(name)
        if found:
            return found
    return None


def html_dimensions(path: str) -> tuple[int, int] | None:
    """Pull the CSS pixel size out of the `html, body { width:Npx; height:Mpx }`
    rule so the screenshot matches whatever the HTML declares."""
    m = re.search(r'html,\s*body\s*\{[^}]*?width:\s*(\d+)px[^}]*?height:\s*(\d+)px',
                  open(path).read())
    return (int(m.group(1)), int(m.group(2))) if m else None


def render_png(chrome: str, port: int, html_path: str, png_path: str) -> bool:
    """Screenshot html_path -> png_path via headless Chrome at 2x device scale.
    Served over HTTP (not file://) so the banner's root-absolute /images/ paths
    and the Google Fonts both resolve. Writes atomically; keeps the old PNG on
    failure."""
    dims = html_dimensions(html_path)
    if not dims:
        print(f"  render SKIP {os.path.relpath(png_path, ROOT)}: no html/body size")
        return False
    w, h = dims
    url = f"http://127.0.0.1:{port}/{os.path.relpath(html_path, ROOT)}"
    tmp = png_path + ".tmp.png"
    cmd = [chrome, "--headless=new", "--disable-gpu", "--hide-scrollbars",
           "--force-device-scale-factor=2", f"--window-size={w},{h}",
           "--default-background-color=00000000", "--virtual-time-budget=10000",
           f"--screenshot={tmp}", url]
    try:
        subprocess.run(cmd, check=True, timeout=120,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        if os.path.exists(tmp):
            os.remove(tmp)
        print(f"  render FAIL {os.path.relpath(png_path, ROOT)}: {exc}")
        return False
    os.replace(tmp, png_path)
    print(f"  rendered    {os.path.relpath(png_path, ROOT)} ({w * 2}x{h * 2})")
    return True


def optimise_png(path: str) -> None:
    """Quantise a freshly-rendered social PNG to a 256-colour palette in place.
    Chrome's screenshots are full 24-bit RGB/RGBA PNGs; these are mostly a flat
    gradient plus a few embedded phone screenshots, so a 256-colour palette
    loses nothing visible while cutting the file to a third of its size or
    better. No new dependency: Pillow is already a soft requirement of the
    render path, guarded here exactly like it is everywhere else -- if it is
    missing, warn and leave the (larger) true-colour PNG in place rather than
    fail the run."""
    try:
        from PIL import Image
    except ImportError:
        print(f"  warning: Pillow not installed, cannot optimise "
              f"{os.path.relpath(path, ROOT)} (pip install pillow)")
        return
    before = os.path.getsize(path)
    im = Image.open(path)
    if im.mode in ("RGBA", "LA") or (im.mode == "P" and "transparency" in im.info):
        # MEDIANCUT/MAXCOVERAGE cannot quantize RGBA; FASTOCTREE is the only
        # alpha-safe method Pillow ships without libimagequant (not installed
        # on this machine -- see Tooling facts).
        quantized = im.convert("RGBA").quantize(colors=256, method=Image.Quantize.FASTOCTREE)
    else:
        quantized = im.convert("RGB").quantize(
            colors=256, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.FLOYDSTEINBERG)
    quantized.save(path, optimize=True)
    after = os.path.getsize(path)
    print(f"  optimised   {os.path.relpath(path, ROOT)}: {before:,} -> {after:,} bytes "
          f"({100 * (1 - after / before):.0f}% smaller)")


def convert_to_jpeg(png_path: str, jpg_path: str) -> None:
    """Convert a rendered per-exam OG card from PNG to JPEG and remove the PNG.
    Per-exam cards are JPEG, not PNG, unlike the two shared images: a card is
    almost entirely flat gradient plus text with no embedded photos, so it
    compresses far smaller as quality-82 JPEG than as a 256-colour PNG palette
    -- comfortably inside the ~150 KB per-card target. Same Pillow guard as
    optimise_png(); if Pillow is missing, the PNG is left behind unconverted
    rather than the run failing."""
    try:
        from PIL import Image
    except ImportError:
        print(f"  warning: Pillow not installed, cannot convert "
              f"{os.path.relpath(png_path, ROOT)} to JPEG")
        return
    im = Image.open(png_path).convert("RGB")
    im.save(jpg_path, "JPEG", quality=82, optimize=True, progressive=True)
    size = os.path.getsize(jpg_path)
    os.remove(png_path)
    print(f"  rendered    {os.path.relpath(jpg_path, ROOT)} ({size:,} bytes)")


def render_exam_cards(chrome: str, port: int, data: dict, retired: set) -> None:
    """Render every exam's OG card: fill apps/AzureMastery/og-exam.html's
    {{CODE}}/{{NAME}}/{{COUNT}} placeholders and its accent custom properties,
    screenshot it via the same render_png() the two shared images use, then
    convert to JPEG. The count always comes from data["exams"][code] -- never
    hand-write it -- and the exam name from the names snapshot refresh_from_app()
    wrote into data/exam-counts.json, so this loop needs no app-repo checkout."""
    if not os.path.exists(OG_EXAM_HTML):
        print("  render SKIP: apps/AzureMastery/og-exam.html missing")
        return
    names = data.get("names") or {}
    counts = {k.upper(): v for k, v in data["exams"].items()}
    template = open(OG_EXAM_HTML).read()
    os.makedirs(OG_DIR, exist_ok=True)
    try:
        for code in sorted(counts):
            count = counts[code]
            name = names.get(code, code)
            accent, accent2 = exam_accent(code)
            page_html = (
                template
                .replace("{{CODE}}", html.escape(code, quote=False))
                .replace("{{NAME}}", html.escape(name, quote=False))
                .replace("{{COUNT}}", str(count))
                .replace("{{ACCENT}}", accent)
                .replace("{{ACCENT2}}", accent2)
            )
            if code in retired:
                page_html, k = PILL_COUNT_RE.subn(PILL_RETIRED, page_html)
                if not k:
                    print(f"  warning: {code} retired-pill swap matched 0 times "
                          f"-- og-exam.html's pill markup may have drifted")
            with open(OG_EXAM_TMP, "w") as fh:
                fh.write(page_html)
            dir_ = code_to_dir(code)
            png_path = os.path.join(OG_DIR, f"{dir_}.png")
            jpg_path = os.path.join(OG_DIR, f"{dir_}.jpg")
            if render_png(chrome, port, OG_EXAM_TMP, png_path):
                convert_to_jpeg(png_path, jpg_path)
    finally:
        if os.path.exists(OG_EXAM_TMP):
            os.remove(OG_EXAM_TMP)


def _serve_root() -> tuple[http.server.ThreadingHTTPServer, int]:
    """Serve ROOT on an ephemeral localhost port in a daemon thread."""
    class Quiet(http.server.SimpleHTTPRequestHandler):
        def log_message(self, *args):  # silence per-request logging
            pass
    handler = functools.partial(Quiet, directory=ROOT)
    httpd = http.server.ThreadingHTTPServer(("127.0.0.1", 0), handler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    return httpd, httpd.server_address[1]


def sync_social_images(p: "Patcher", counts: dict, total_label: str,
                       exam_count: int, cert_paths: int, render: bool,
                       data: dict, retired: set) -> None:
    print("social images:")
    p.apply(BANNER_HTML, banner_edits(total_label, exam_count))
    p.apply(OG_HTML, og_edits(total_label, exam_count, cert_paths))
    warn_pill_drift(BANNER_HTML, counts, exam_count)
    warn_pill_drift(OG_HTML, counts, exam_count)

    if p.check_only or not render:
        return
    chrome = find_chrome()
    if not chrome:
        print("  render SKIP: no Chrome/Chromium found "
              "(install Google Chrome or set env CHROME); PNGs left unchanged")
        return
    httpd, port = _serve_root()
    try:
        if render_png(chrome, port, BANNER_HTML, BANNER_PNG):
            optimise_png(BANNER_PNG)
        if render_png(chrome, port, OG_HTML, OG_PNG):
            optimise_png(OG_PNG)
        print("exam OG cards:")
        render_exam_cards(chrome, port, data, retired)
    finally:
        httpd.shutdown()


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--refresh", action="store_true",
                    help="re-read counts from the app repo into data/exam-counts.json")
    ap.add_argument("--check", action="store_true",
                    help="report files that would change; write nothing")
    ap.add_argument("--social-only", action="store_true",
                    help="only sync the social images (banner + og-image)")
    ap.add_argument("--no-render", action="store_true",
                    help="patch HTML/counts but skip rendering the social PNGs")
    ap.add_argument("--app-repo", default=DEFAULT_APP_REPO,
                    help=f"path to the AZ-104 Mastery checkout (default: {DEFAULT_APP_REPO})")
    args = ap.parse_args()

    data = refresh_from_app(args.app_repo) if args.refresh else load_data()

    # counts = the advertised per-exam number for every page, including the
    # non-current ones. active = the subset that feeds headline aggregates.
    counts = {k.upper(): v for k, v in data["exams"].items()}
    retired = non_current_exams(data)
    active = {code: n for code, n in counts.items() if code not in retired}
    # catalogue_count = every exam page that exists (sit-able + retired
    # reference pages) — the basis for the homepage ItemList's numberOfItems,
    # which is deliberately not exam_count.
    catalogue_count = len(counts)

    # Aggregates are read verbatim from the app's generated catalog-totals.json
    # rather than summed here — that file is what the App Store listing quotes,
    # and recomputing would let the two drift apart again.
    totals = data.get("totals") or {}
    if not totals:
        sys.exit("error: data/exam-counts.json predates catalog-totals.json — "
                 "re-run with --refresh against the app repo.")
    total = totals["questionCount"]
    exam_count = totals["examCount"]
    total_label = totals["questionCountLabel"]      # prose, e.g. "10,300+"
    metric_total = str((total // 100) * 100)        # comma-less for the count-up
    cert_paths = data.get("cert_path_count") or 0

    if exam_count != len(active):
        print(f"  warning: totals say {exam_count} current exams, catalogue lists "
              f"{len(active)} — re-run with --refresh.")

    print(f"counts: {exam_count} current exams, {total} exam-scoped questions "
          f"-> label {total_label} (metric {metric_total}), {cert_paths} current cert paths")
    if retired:
        print(f"        non-current, excluded from aggregates: {', '.join(sorted(retired))}")

    p = Patcher(check_only=args.check)

    if not args.social_only:
        print("exam pages:")
        for code, n in sorted(counts.items()):
            page = os.path.join(EXAMS_DIR, code_to_dir(code), "index.html")
            if not os.path.exists(page):
                print(f"  skip (missing): exams/{code_to_dir(code)}/index.html")
                continue
            # own-exam anchored edits
            original = open(page).read()
            text = original
            for pat, rep in exam_page_edits(code, n):
                text = re.sub(pat, rep, text)
            # cross-referenced related cards (any exam -> its count)
            text, _ = patch_related_cards(text, counts)
            rel = os.path.relpath(page, ROOT)
            if text != original:
                p.changed_files += 1
                if args.check:
                    print(f"  DRIFT  {rel}")
                else:
                    open(page, "w").write(text)
                    print(f"  synced {rel}")

        print("homepage:")
        p.apply(INDEX_HTML,
                homepage_edits(total_label, metric_total, exam_count, cert_paths,
                               len(retired), catalogue_count),
                transforms=[lambda t: patch_exam_code_lists(t, retired),
                            lambda t: patch_more_certifications(t, exam_count, retired),
                            lambda t: patch_roadmap_category_counts(t, retired)])

        print("llms.txt:")
        p.apply(LLMS_TXT, llms_edits(counts, total_label, exam_count),
                transforms=[lambda t: patch_llms_section_counts(t, retired)])

        warn_retired_markup(p, retired, set(counts))
        warn_itemlist_count(catalogue_count)

    sync_social_images(p, active, total_label, exam_count, cert_paths,
                       render=not args.no_render, data=data, retired=retired)

    verb = "would change" if args.check else "changed"
    print(f"\n{p.changed_files} file(s) {verb}.")
    if p.problems:
        print(f"{p.problems} markup problem(s) need a hand fix — see RETIRED lines above.")
    if args.check and (p.changed_files or p.problems):
        sys.exit(1)


if __name__ == "__main__":
    main()
